Repository apache/pekko, pull requests merged in 2023-06, with the labels that each got.

#385 CVE-2023-31442 Address DNS poisoning vulnerability
  actor-tests/src/test/scala/org/apache/pekko/io/dns/DnsSettingsSpec.scala
  actor-tests/src/test/scala/org/apache/pekko/io/dns/IdGeneratorSpec.scala
  actor-tests/src/test/scala/org/apache/pekko/io/dns/internal/AsyncDnsResolverSpec.scala
  actor-tests/src/test/scala/org/apache/pekko/io/dns/internal/DnsClientSpec.scala
  actor/src/main/resources/reference.conf
  actor/src/main/scala/org/apache/pekko/io/dns/DnsSettings.scala
  actor/src/main/scala/org/apache/pekko/io/dns/IdGenerator.scala
  actor/src/main/scala/org/apache/pekko/io/dns/internal/AsyncDnsResolver.scala
  actor/src/main/scala/org/apache/pekko/io/dns/internal/DnsClient.scala
  actor/src/main/scala/org/apache/pekko/io/dns/internal/Question.scala
  bench-jmh/src/main/scala/org/apache/pekko/io/dns/IdGeneratorBanchmark.scala
Labels: async-dns-resolver

#371 Generate random DNS id's
  actor/src/main/resources/reference.conf
  actor/src/main/scala/org/apache/pekko/io/dns/DnsSettings.scala
  actor/src/main/scala/org/apache/pekko/io/dns/IdGenerator.scala
  bench-jmh/src/main/scala/org/apache/pekko/io/dns/IdGeneratorBanchmark.scala
Labels: bug, async-dns-resolver

#433 Add note to LICENSE files regarding AbstractBoundedNodeQueue origin
  LICENSE
  legal/pekko-actor-jar-license.txt
Labels: licensing

#427 Delete PrettyByteString.scala
  actor/src/main/scala/org/apache/pekko/util/PrettyByteString.scala
Labels: licensing

#436 better acknowledge code derived from scala-library
  LICENSE
  actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/package.scala
  actor/src/main/scala/org/apache/pekko/util/Helpers.scala
  legal/pekko-actor-jar-license.txt
Labels: licensing

#438 acknowledge use of hash-prospector code
  LICENSE
  actor/src/main/scala/org/apache/pekko/util/FrequencySketch.scala
  legal/pekko-actor-jar-license.txt
Labels: licensing

#449 acknowledge use of Play Samples scripts
  LICENSE
Labels: licensing

#446 add license information for Caffeine code used in FrequencySketch
  LICENSE
  actor/src/main/scala/org/apache/pekko/util/FrequencySketch.scala
  legal/pekko-actor-jar-license.txt
Labels: licensing
